-- 코드를 입력하세요
SELECT  TITLE, USED_GOODS_REPLY.BOARD_ID, USED_GOODS_REPLY.REPLY_ID,USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.created_date, '%Y-%m-%d') as CREATED_DATE

from USED_GOODS_BOARD
 join USED_GOODS_REPLY 
on USED_GOODS_REPLY.BOARD_ID = USED_GOODS_BOARD.BOARD_ID
where USED_GOODS_BOARD.created_date like '%2022-10%'
order by USED_GOODS_REPLY.CREATED_DATE asc, USED_GOODS_BOARD.title asc

;